export const TABLE_DATA_FETCHING = "TABLE_DATA_FETCHING"
export const TABLE_DATA_SUCCESS = "TABLE_DATA_SUCCESS"
export const TABLE_DATA_ERROR = "TABLE_DATA_ERROR"
export const TABLE_DATA_CHANGE_PAGE = "TABLE_DATA_CHANGE_PAGE"